site_name: VidracariaModelo
site_url: https://mdsreq-fga-unb.github.io/2025.1-T01-VidracariaModelo/
repo_url: https://github.com/mdsreq-fga-unb/2025.1-T01-VidracariaModelo

theme:
  name: material
  features:
    - navigation.sections
  palette:
    primary: indigo
    accent: blue
  navigation:
    expand: false

extra_css:
  - overrides/extra.css

nav:
  - Home: index.md
  - Visão de Projeto: 
    - 1. Cenário Atual do Cliente e do Negócio: docs/VisaodeProduto/Cenario_atual.md
    - 2. Solução Proposta: docs/VisaodeProduto/Solucao_proposta.md
    - 3. Estratégias de Engenharia de Software: docs/VisaodeProduto/Estrategias.md
    - 4.Cronograma e Entregas: docs/VisaodeProduto/Cronograma.md
    - 5.Interação entre Equipe e Cliente: docs/VisaodeProduto/Interacao.md
    - 6. Lições Aprendidas: docs/VisaodeProduto/licoes.md

  - Atas de Reunião:
      - 15/04: docs/Atas/15_04.md
