site_name: VidracariaModelo
site_url: https://mdsreq-fga-unb.github.io/2025.1-T01-VidracariaModelo/
repo_url: https://github.com/mdsreq-fga-unb/2025.1-T01-VidracariaModelo

theme:
  name: material
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.top
    - navigation.tracking
  palette:
    primary: indigo
    accent: blue
  navigation:
    expand: false

extra_css:
  - overrides/extra.css

nav:
  - Home: index.md
  - Visão de Projeto: 
    - 1. Cenário Atual do Cliente e do Negócio: docs/VisaodeProduto/Cenario_atual.md
    - 2. Solução Proposta: docs/VisaodeProduto/Solucao_proposta.md
    - 3. Estratégias de Engenharia de Software: docs/VisaodeProduto/Estrategias.md
    - 4.Cronograma e Entregas: docs/VisaodeProduto/Cronograma.md
    - 5.Interação entre Equipe e Cliente: docs/VisaodeProduto/Interacao.md
    - 6. Lições Aprendidas: docs/VisaodeProduto/licoes.md
  - Requisitos: docs/requisitos/requisitos.md
  
  - Entregas: 
    - 1º Entrega: docs/Entregas/1.md

  - Atas de Reunião:
      - 15/04: docs/Atas/15_04.md
      - 29/04: docs/Atas/29_04.md
      - 06/05: docs/Atas/06_05.md
      - 13/05: docs/Atas/13_05.md
      - 20/05: docs/Atas/20_05.md
