site_name: VidracariaModelo
repo_url: https://github.com/mdsreq-fga-unb/2025.1-T01-VidracariaModelo

site_url: https://mdsreq-fga-unb.github.io/2025.1-T01-VidracariaModelo/


theme:
  name: mkdocs
  features:
    - navigation.tabs  # Habilita abas de navegação superiores
    - navigation.top   # Fixa a navbar no topo
  
  # Personalização de cores (opcional)
  palette:
    primary: indigo
    accent: blue

nav:
  - Home: index.md
  - Documentação: docs/Documentação/VPP.md
  - Atas de Reuniao: 
    - 15/04: docs/Atas/15_04.md