site_name: Meu Projeto
theme:
  name: material
  # Paleta de cores (escolha uma combinação)
  palette:
    - scheme: default
      primary: indigo       # Cor principal (navbar)
      accent: pink          # Cor de destaques
      toggle:
        icon: material/brightness-4  # Ícone de tema
        name: Alternar tema
  # Barra superior personalizada
  features:
    - navigation.tabs       # Abas no topo
    - navigation.top        # Barra fixa no topo

# Navegação
nav:
  - Início: index.md
  - Contato: contato.md

# CSS/JS extra (opcional)
extra_css:
  - stylesheets/extra.css   # Para mais personalizações