site_name: Meu Projeto
theme:
  name: mkdocs
  features:
    - navigation.tabs  # Habilita abas de navegação superiores
    - navigation.top   # Fixa a navbar no topo
  
  # Personalização de cores (opcional)
  palette:
    primary: indigo
    accent: blue

nav:
  - Home: index.md
  - Documentação: Documentação/VPP.md
  - Atas de Reuniao: 
    - 15/04: Atas/15_04.md